1Password/connect-helm-charts

connect/README.md
connect/templates/NOTES.txt
connect/templates/connect-credentials.yaml
connect/templates/connect-deployment.yaml
connect/templates/operator-deployment.yaml
connect/templates/operator-token.yaml
connect/templates/service.yaml
connect/values.yaml

Helm already has a way to set the target namespace, which we were ignoring. 
This PR uses `.Release.Namespace` as the target namespace now, so you can run `helm install` with `--namespace my-namespace` instead of `--set namespace=my-namespace`.
Also, the `WATCH_NAMESPACE` var will default to `.Release.Namespace`.

Use native namespace setting

---

connect/README.md

Providing the actual flag to set, makes it a little easier to use and also clarifies the correct name for operator.token.value.
Resolves: #16.

Provide concrete examples for --set flag usage

---

connect/templates/service.yaml

This will let Kubernetes find a free port, resolving issues with the port already being acquired by another service.
This should also resolve #22.

Remove fixed specification of NodePort

---

connect/templates/connect-deployment.yaml
connect/templates/operator-deployment.yaml
connect/templates/rolebinding.yaml
connect/values.yaml

Add security context to Connect and Operator containers 
Resolves #12 
- Connect api and sync default to user 999
- Operator defaults to 65532 according to [base image documentation](https://github.com/GoogleContainerTools/distroless/blob/2e539660094d9c2910f6134df1d0d3919479c393/base/base.bzl#L9)
- Neither container is allowed to escalate permissions
- Add multicast capabilities to the `connect-api` and `connect-sync` containers
Also resolve templating issue with Role Binding
- Inside of range the context needs to be $
- The default value for `watchNamespace` should be an empty list rather than empty string namespace

Define default Security Contexts for containers

---

scripts/prepare-release.sh

We do not want the release branch to track remote main... It should track the release branch.

Set correct remote branch in release script

---

connect/README.md
connect/templates/operator-deployment.yaml
connect/templates/rolebinding.yaml
connect/values.yaml

When setting `--namespace`, you'd expect that by default the specified namespace would be watched by the operator.
This was addressed already in https://github.com/1Password/connect-helm-charts/pull/18, but was [reverted](https://github.com/1Password/connect-helm-charts/pull/25/commits/3cae01c755d141cd46bff849c8302fe22a57f12b) due to breaking the cluster role bindings. This PR resolves that.
Small note on the implementation: `values.yaml` doesn't support interpolation directly. So as a workaround, we have to interpolate `.Release.Namespace` on the template side using the `tpl` function.

Watch .Release.Namespace by default

---

.github/workflows/lint.yml
.github/workflows/test.yml
artifacthub-repo.yml
connect/Chart.yaml
connect/ci/with-operator-values.yaml
connect/templates/tests/health-check.yml
connect/templates/tests/secret-read.yml
connect/templates/tests/setup-secret-read.yml
connect/values.yaml
ct.yaml

This PR adds GitHub Actions workflows for linting and testing the Helm chart.
For the test, it will check if the chart has changed compared to the upstream, and if so, it spins up a local Kubernetes cluster and deploys Connect and the operator.
Then it deploys another pod onto the cluster that performs a health check of the Connect instance.
And to finish it off, it deploys a OnePasswordItem CRD that references a test secret and it deploys another pod onto the cluster that tries to load that test secret as a Kubernetes Secret.

Create Actions workflows for CI

---

connect/README.md
connect/ci/with-operator-values.yaml
connect/templates/clusterrole.yaml
connect/templates/rolebinding.yaml
connect/templates/serviceaccount.yaml
connect/values.yaml

Previously, to get an out-of-the-box working operator, you'd have to add 4 flags: `--set operator.create=true --set operator.clusterRole.create=true --set operator.serviceAccount.create=true --set operator.roleBinding.create=true`.
This PR changes this behavior by taking whatever value the `operator.create` flag has as the default value of the RBAC resource creation flags.
So now, you only have to add `--set operator.create=true` and you get the correct RBAC setup. The resources can still individually be disabled by explicitly setting them to `false`.

Create RBAC resources by default when operator is enabled

---

connect/README.md
connect/crds/onepassworditem-crd.yaml

As per the [Helm 3 recommendations](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) the CRD is now removed from the `templates` dir to the `crds` dir. This does mean that we lose the ability to template.
So previously, the way to skip the CRD would be `--set operator.create=false`, but now you'd have to set `--skip-crds`.

Move CRD out of templates into crds dir

---

connect/README.md

Even though curly braces with spaces is more standard, removing these spaces bypasses line breaks, which makes it more readable.

Improve readability of values table in README

---

.github/workflows/release.yml
CHANGELOG.md
charts/connect/Chart.yaml

* New Helm repo URL: https://1password.github.io/connect-helm-charts {#41}
* Connect server updated to `v1.1.0` {#40}
* Operator version updated to `v1.0.1` {#42}
* CRD now lives in `crds/` dir, so they can be skipped with the `--skip-crds` flag {#36}
* RBAC resources will be created by default when operator is enabled {#37}
* `.Release.Namespace` is now watched by the operator by default {#32}

Release connect chart v1.2.0

---

charts/connect/README.md
charts/connect/templates/connect-deployment.yaml
charts/connect/templates/operator-deployment.yaml
charts/connect/values.yaml

In some use-cases, labels and annotations are used for enhanced monitoring, Prometheus scraping etc. 
So this adds 4 new values. 
Deployment Annotation & Labels -i.e. for the deployment resource itself
Pod Annotation & Labels - i.e. added to the template and these are passed down to the pod created by the deployment. 
An example values.yaml:
```
nodeSelector: {}
annotations: {}
labels: {}
podAnnotations:
prometheus.io/port: "8080"
prometheus.io/scrape: "true"
podLabels: {}
```

Offer additional labels & annatations for deployments

---

.github/workflows/test.yml

Not so pretty, but a better-than-nothing solution to be able to run the acceptance tests for external PRs after having manually validated them.
Do a manual sanity check on the submitted code and copy the branch's latest commit hash, go to the `Actions` tab -> `Run acceptance tests` and press the `Run workflow` button (note: button doesn't show yet, because this PR needs to be on `main` first). Paste in the commit hash you verified and enter the fork repository name, and it will run the acceptance tests including the secrets needed to run the tests.
- No automatic reporting back to the PR
- We have to keep a branch / commit open to attach all the workflow runs to, to avoid messing up our main branch commits with false alarm red Xs. I've created …

Add support for on-demand CI acceptance test runs

---

charts/connect/templates/rolebinding.yaml
charts/connect/templates/serviceaccount.yaml

`ClusterRoleBinding` grants the permissions cluster wide. Instead, now we limit the permissions to just the namespaces being  watched by using a `RoleBinding` instead following the principle of least privilege.
- https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding

Follow principle of least privilege for operator permissions

---

charts/connect/README.md
charts/connect/templates/NOTES.txt

These pages have been moved permanently, so we could better direct users to the new pages directly.

Update links to the support page

---

charts/connect/Chart.yaml
charts/connect/README.md
charts/connect/templates/_helpers.tpl
charts/connect/templates/connect-deployment.yaml
charts/connect/templates/operator-deployment.yaml
charts/connect/templates/service.yaml
charts/connect/templates/tests/health-check.yml
charts/connect/values.yaml

Exposes `connect.tls.enabled` and `connect.tls.secret` to enable TLS for the Connect server. The `connect.tls.secret` should contain the name of a secret that contains `tls.key` and `tls.crt` value (as is standard for TLS configuration in Kubernetes).
One point for consideration: do we want to use `connect.tls.secret` or `connect.tls.secretName`?

TLS support

---

charts/connect/README.md
charts/connect/templates/clusterrolebinding.yaml
charts/connect/templates/operator-deployment.yaml
charts/connect/templates/rolebinding.yaml
charts/connect/values.yaml

I needed this for something I was working on, but I noticed #62 was kinda stalled. Thanks to @rchenzheng for doing all of the hard work. This PR addresses the comments in #62.
This change creates a ClusterRoleBinding conditionally if all namespaces are to be watched. By default, all namespaces are watched, to match the default behaviour when deploying the operator. This behaviour can be explicitly opted into by specifying an empty list for `operator.watchNamespace`.
See also:
#54
https://github.com/1Password/onepassword-operator/pull/40

Watch all namespaces for secrets (attempt 2)

---

charts/connect/templates/connect-deployment.yaml

Corrects the name of the value that's being references to get the resources block for the api container

Correct resources value name

---

charts/connect/Chart.yaml
charts/connect/templates/connect-deployment.yaml

As requested in both https://github.com/1Password/connect/issues/22 and https://github.com/1Password/connect/issues/21, this removes the need for the containers to obtain the `NET_BROADCAST` capability by no longer depending on the auto-discovery of each other.
Bumps Connect to `1.5.0` to use the new `OP_BUS_PEERS` option.

Remove need for NET_BROADCAST

---

charts/connect/README.md
charts/connect/templates/connect-credentials.yaml
charts/connect/values.yaml

Resolves the issue brought up in #67 that Terraform has issues with providing the raw JSON value as input to the Helm chart.

Add support for passing `connect.credentials` as base64-encoded value

---

CHANGELOG.md
charts/connect/Chart.yaml
charts/connect/README.md

* Connect can now run with fully unprivileged containers. {#21,#22}
* Tolerations can now be configured with `connect.tolerations` and `operator.tolerations`. {#63}
* Resource type for the Connect Service is now configurable. {#65}
* Updated Connect to [v1.5.0](https://github.com/1Password/connect/blob/main/CHANGELOG.md#v150). {#81}
* Base64-encoded credentials can be supplied through `connect.credentials_base64` if passing raw JSON through `connect.credentials` leads to issues. {#67}
* Resources are now correctly passed to the Connect API container. {#79}
Thanks to @rowa78, @parente, @mcmarkj for their code contributions! 🙌

Release connect-1.7.0

---

CHANGELOG.md
charts/connect/Chart.yaml

* Updated Kubernetes Operator to v1.5.0, which adds the `type` and `status` for the `OnePasswordItem` CRD. {#101}
* Updated OnePasswordItem CRD to enable the new functionality added in the latest version of the Kubernetes Operator. Shoutout to @tomjohnburton for contributing to this enhancement. {#92, #102}
* Updated Connect to v1.5.4, which resolves some bugs. {#101}

Prepare release of connect-1.8.0

---

CHANGELOG.md
charts/connect/Chart.yaml

Updates Connect to v1.5.6, which has the following updates (from v1.5.4):
- [FIXED] Connect now properly returns the `content_path` attribute of the File object.
- [FIXED] The file objects now have the correct ID and name.
- [FIXED] Categories route will no longer return status 500 when no error is present.
- [SECURITY] Updated Debian packages for the Docker release images.
This will also release 1.8.1 of the Connect Helm chart

Update Connect to v1.5.6

---

README.md

This `$` serves no purpose without any output shown. Removing it, makes it easier to copy the command.

Remove $ from copyable command

---

charts/connect/README.md
charts/connect/templates/connect-deployment.yaml
charts/connect/values.yaml

Hi, I hope this PR is in line with the contributing guidelines, otherwise I'm happy to adjust it as you see fit. 😄 
This simple PR is here to enable user deployments to run with more replicas to have more stability and redundancy in case of any unexpected error like the running Pod getting evicted or something and there isn't another one available to fulfill the incoming requests making other applications fail to start. What do you think about it?

feat: add deployment replicas to values

---

README.md
charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

* Add replicas definition to the Connect Deployment {#121, #128}
* Use the latest 1password/operator version 1.6.0 {#128}
* Use '1Password Operator' term instead of '1Password Connect Operator' in the documentation {#128}

Prepare release of connect-1.10.0

---

charts/connect/README.md

The README states that the default value for the key `connect.credentialsKey` is `op-session`.
We update this value to `1password-credentials.json` to be coherent with `values.yaml`.

docs: update connect.credentialsKey default value

---

charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

* Extra service annotations can now be specified with `connect.serviceAnnotations`. {#106}
* `connect.create` can now be used to control whether a Connect instance should be created. {#125}
* The default Connect version is updated to v1.7.0.
* The default value of `connect.CredentialsKey` is now correctly documented. {#136}
Thanks @twink0r, @lapwat, @leehanel, @Matthiasvanderhallen for your contributions.

Release connect-1.11.0

---

charts/connect/values.yaml

This makes the default value consistent w/ the helm chart README, and the k8s operator README.

Update operator default pollingInterval to 600 seconds

---

charts/connect/README.md

Warn about the usage of the base64 format to store the secret

Improve the description of the connect.credentialsKey entry

---

charts/connect/Chart.yaml
charts/connect/templates/_helpers.tpl
charts/connect/templates/connect-deployment.yaml
charts/connect/values.yaml

This will help us debug some of the reported memory leaks.
An extra container is added if the profiler is enabled to allow copying the profiler data out of the pod. This is needed because the Connect images are distroless and therefore do not support `kubectl cp`.
If enabled, data can be exported by running:
```
kubectl cp -c profiler-data <pod>:/data profiler
```

Add option to enable profiler

---

charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

* Connect's log level can now be specified using connect.api.loglevel and connect.sync.logLevel. {#135}
* The default Connect version is updated to v1.7.1.
* Connect's profiler can now be enabled through the Helm chart to help 1Password debug memory and performance issues. {#157} 
* Ingress now correctly works if TLS is enabled. {#140}
* The operators's polling interval is now consistent with the readme's. {#147}
* The readme now correctly mentions the Connect's credential file must be base64-encoded. {#155}
Thanks @antham, @akohlmann, @Altiire, @JoshCooley-alto for your contributions.

Prepare release connect-1.12.0

---

charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

* Distinct standalone operator Helm deployments use the same lock. {#148}

Prepare release connect-1.12.1

---

charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

This release includes the following:
* Upgraded to default to version 1.7.1 of the Operator. {#164}
* The Connect helm char now supports the ability to set the logging level on the Operator. {#164}

Preparing release connect-1.13.0

---

charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

This PR bumps the Connect version used by Helm charts to v1.7.3.
This PR will also make a new Helm chart release which will use Connect v1.7.3

Update to Connect 1.7.3

---

charts/connect/values.yaml

The default values were estimated during experiments

Add sensible defaults to limit connect-api's resource consumption

---

charts/connect/values.yaml

Since CPU is a compressible resource it makes sense for us not to limit it. Furthermore, since we want to meet the conditions for our node to be catalogued as `burstable` by Kubernetes we want to provide a `request` spec.

Use request instead of limits for cpu resource

---

charts/connect/templates/connect-pdb.yaml
charts/connect/templates/operator-pdb.yaml
charts/connect/values.yaml

Current pod disruption budget objects are not working correctly because of their labels. The labels matching the pods use the deployment labels instead of the pod ones. Because of that, the `pdbs` never identify the pods managed by the deployments.
Deployment labels
```yaml
app.kubernetes.io/component=connect
app.kubernetes.io/instance=connect
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=connect
app.kubernetes.io/version=1.7.3
helm.sh/chart=connect-1.16.0
```
Pod labels
```yaml
app=onepassword-connect
app.kubernetes.io/component=connect
```
A second issue identified in the pod disruption objects is the lack of an option to set up the `minAvailable` feature. The solution included in the merge request allows the use of `minAvailable` or `maxUnavailable`.

Fix podDisruptionBudget labels

---

charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

* Add resources defaults to limit connect API's resource consumption. (#209, #211)
* Fix `podDisruptionBudget` labels. Credits to @mmorejon for the contribution. (#213)

Prepare Connect Helm chart release 1.17.0

---

.github/workflows/lint.yml
.github/workflows/test.yml
charts/connect/Chart.yaml
charts/connect/templates/clusterrole.yaml

- Adds conditional templating logic that prevents the helm template from generating unnecessary rules for 1Password Connect Operator when serviceMonitor support is disabled.
- Fixes lint workflow by updating python version from 3.7 to 3.12.
- Enables execution of test workflow in forked repositories by allowing optional injection of vault id, item id and secret value using repository variables.
- #224

#224 Remove permissions when serviceMonitor.enabled is false

---

charts/connect/CHANGELOG.md
charts/connect/Chart.yaml

I was wondering if it would be possible to have a release for connect helm chart which includes a bugfix from #241 . It would help me a bit. To speed up the process, I created this PR with a release 2.0.3 while following what was done for 2.0.2 in https://github.com/1Password/connect-helm-charts/pull/237
Sorry for brevity.
cc @volodymyrZotov

Prepare release v2.0.3 for connect chart
