- connect/README.md
- connect/templates/connect-deployment.yaml
- connect/templates/operator-deployment.yaml
- connect/values.yaml
This will allow for pinning the pods on specific nodes :-)
> Add nodeSelector option to Helm charts

- connect/templates/connect-deployment.yaml
Previous commit added a duplicate key.
> Remove duplicate key

- Makefile
- scripts/prepare-release.sh
Made a few minor changes to make life a little easier during a release. See the commits for what changed.
Also fixes the non-fix of https://github.com/1Password/connect-helm-charts/pull/27 (it did not do what I expected and I did not test it thoroughly enough).
> Improve release script

- charts/connect/README.md
- charts/connect/templates/operator-deployment.yaml
- charts/connect/values.yaml
It's best practice to set resource limits. You can set it for the connect server but not the operator, so adding that option.
> Add resource obj to the operator

- CHANGELOG.md
- charts/connect/Chart.yaml
* Connect server updated to `v1.2.0` {#49}
* Resource limits can now be set on the operator {#52}
* Additional labels & annotations are set for deployments {#51}
* Follow principle of least privilege for operator permissions {#55}
> Release 1.3.0

- charts/connect/README.md
- charts/connect/templates/_helpers.tpl
- charts/connect/templates/connect-deployment.yaml
- charts/connect/values.yaml
Same as #50 by @mcmarkj with changes to support for custom ports and TLS.
> Add connect liveness

- CHANGELOG.md
- charts/connect/Chart.yaml
* API and Sync containers now have liveness and readiness probes. {#47}
* The Connect API can now be configured to use TLS with a custom certificate.
Thanks to @mcmarkj for their contribution on the liveness and readiness probes!
> Release v1.4.0

- charts/connect/README.md
- charts/connect/templates/clusterrolebinding.yaml
- charts/connect/templates/operator-deployment.yaml
- charts/connect/values.yaml
- create clusterrolebinding conditionally
- default to watching all namespaces
RE:
https://github.com/1Password/onepassword-operator/pull/40
https://github.com/1Password/connect-helm-charts/issues/54
> Watch all namespaces for secrets

- CHANGELOG.md
- charts/connect/Chart.yaml
* Add clusterrolebinding compatibility and watch all namespaces by default. {#62}
Thanks to @rchenzheng and @Gibstick for their contribution on the clusterrolebinding compatibility and enabling to watch all namespaces by default.
> Release v1.5.0

- CHANGELOG.md
- charts/connect/Chart.yaml
* Add `app.kubernetes.io/component` labels for Connect and Operator. {#70}
Thanks to @lhriley for contributing this change! :heart:
> Release v1.6.0

- charts/connect/README.md
- charts/connect/templates/connect-deployment.yaml
- charts/connect/templates/operator-deployment.yaml
- charts/connect/values.yaml
I added the possibility to specify tolerations to this helm-chart.
> added tolerations in helm-templates

- charts/connect/crds/onepassworditem-crd.yaml
This is done to enable using the latest functionality added to the OnePasswordItem with the Helm charts as well.
> Bump OnePasswordItem CRD based on latest version of operator

- CHANGELOG.md
- charts/connect/Chart.yaml
* Enable a better interaction with 1Password Connect and Sync applications deployed. Credits to @klaus385 for contributing to this enhancement. {#107}
* Updated Connect to v1.5.7, which addresses some bugs and security enahncements.
> Prepare release of connect-1.9.0

- charts/connect/README.md
Updated the README to introduce greater delineation between Connect deployment instructions and Connect Operator deployment instructions.
> [DOCS] Update Readme.md

- charts/connect/README.md
- charts/connect/templates/_helpers.tpl
- charts/connect/templates/service.yaml
- charts/connect/values.yaml
Fixes https://github.com/1Password/connect-helm-charts/issues/106
> 🔧 Add serviceAnnotations

- charts/connect/README.md
- charts/connect/templates/connect-deployment.yaml
- charts/connect/values.yaml
Exposes env vars to set loglevel for api and sync components
> exposes loglevel of connect components

- charts/connect/templates/ingress.yaml
fix https://github.com/1Password/connect-helm-charts/issues/140
> [FIX] charts - default service name for tls

- charts/secrets-injector/CHANGELOG.md
- charts/secrets-injector/Chart.yaml
This updates the image to 1.0.2 and fixes a silly typo.
Thanks to @antoineco for originally opening #149
> Prepare release secrets-injector 1.0.1

- charts/connect/CHANGELOG.md
- charts/connect/Chart.yaml
This release includes:
* Add ability to set Priority Class Name. Credits to @jonas-zipprick for the contribution. {#201}
* Add a way to set imagePullSecrets to deployments. Credits to @luflow for the contribution. {#203}
* Add HPA, PDB and Pod Affinity for both Operator and Connect components. Credits to @dapama for the contribution. {#170}
> Release connect-helm-chart v1.16.0

- charts/secrets-injector/CHANGELOG.md
- charts/secrets-injector/Chart.yaml
This release includes the following:
* Custom Environment Variable Support. {#152}
* Add a way to set imagePullSecrets to deployments. Credits to @luflow for the contribution. {#203}
> Release secrets-injector v1.1.0
